### ISSUE TITLE
readthedocs haven't rebuilt in over a year 

### ISSUE THREAD

**Issue by ianhi** [cytoscape/ipycytoscape#305]
https://ipycytoscape.readthedocs.io/en/latest/ is still on version 1.0.3 and looking at https://readthedocs.org/projects/ipycytoscape/ it seems it was last built 1 year and 3 months ago 
![image](https://user-images.githubusercontent.com/10111092/151823746-481ead23-d708-4904-9461-60e6818647b1.png)

@marimeireles can you either have a go at fixing this and/or add me as a maintainer to the docs so I can try?

I suspect changing the repo source might help, and also possibly what triggers doc builds.

**Comment by marimeireles** [comment]
Hey @ianhi.
I don't know what broke the badge. The docs are passing, 2 days ago when you opened this I rebuilt them.
I'll look into to how to add you.
The problem with the docs is that they don't have a hook with PRs? Or they're not working, I don't remember anymore.
+ They're building and passing fine but the animated examples you added aren't working anymore because the API is not backwards compatible. So we have to fix that! :)

**Comment by jenshnielsen** [comment]
To me it looks like https://ipycytoscape.readthedocs.io/en/latest/ has not been updated in a while but https://ipycytoscape.readthedocs.io/en/master/ seens to be up to date.
